---
- name: Install phpbuild required packages
  yum:
    name: "{{ phpbuild_packages | join(',') }}"
    state: present

- name: Install phpbuild required packages libzip-devel
  yum:
    name: libzip-devel
    state: present
  when: ansible_distribution == "Amazon" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")

- name: Install remi repository
  import_role:
    name: cloud3rsio.yumrepo_remi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Install phpbuild required packages libzip-last-devel
  yum:
    name: libzip-last-devel
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Check phpbuild directory
  stat:
    path: "{{ phpbuild_destination }}"
  register: phpbuild_dest

- name: Install phpbuild
  git:
    repo: https://github.com/php-build/php-build.git
    dest: "{{ phpbuild_destination }}"
    version: "{{ phpbuild_version }}"
  when: not phpbuild_dest.stat.exists

- name: Setup profile
  template:
    src: phpbuild.sh.j2
    dest: /etc/profile.d/phpbuild.sh
    owner: root
    group: root
    mode: 0644
